
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/dailymemo
      username: root
      password: 123654


  thymeleaf:
    cache: false

  resources:
    cache:
      period: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true


