
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/dailymemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: root
      password: 123654
      connection-test-query: SELECT 1

  thymeleaf:
    cache: false

  resources:
    cache:
      period: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true


